import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { CreateMeetingProvider } from './context/CreateMeetingContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'YouWork',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <CreateMeetingProvider>{children}</CreateMeetingProvider>
      </body>
    </html>
  );
}
