import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { CreateMeetingProvider } from './context/CreateMeetingContext';
import ClientThemeProvider from './components/ClientThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'YouWork',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <ClientThemeProvider>
          <CreateMeetingProvider>{children}</CreateMeetingProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
