import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ClientThemeProvider from './components/ClientThemeProvider';
import { MeetingProvider } from './context/MeetingContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'YouWork',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <ClientThemeProvider>
          <MeetingProvider>{children}</MeetingProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
